# title: Sakshi Rathi
# logo: /assets/img/edit5.png
# description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal

# Site configuration
title: "Sreya Reddy"
logo: /assets/img/edit5.png
description: "MS Data Science @ CU Boulder | ML • Analytics • Visualization"
show_downloads: false

# User site → baseurl must be empty
baseurl: ""
url: "https://sreyareddyn.github.io"

theme: jekyll-theme-minimal # You can choose a theme that suits your style
